/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppLayout {
    }
    interface AppNav {
    }
    interface GuideList {
        "guideId": string;
    }
    interface GuidePage {
    }
    interface GuideView {
        "guideId": string;
    }
    interface LatestRelease {
    }
    interface ProjectPage {
        "heroImage"?: string;
        /**
          * @default ''
         */
        "pageTitle": string;
        "tagline"?: string;
    }
    interface SkillPointsCard {
        /**
          * @default 'Skill Points'
         */
        "cardTitle": string;
        "guideId"?: string;
        /**
          * @default []
         */
        "skills": SkillEntry[];
        /**
          * @default []
         */
        "tabs": SkillTab[];
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppLayoutElement extends Components.AppLayout, HTMLStencilElement {
    }
    var HTMLAppLayoutElement: {
        prototype: HTMLAppLayoutElement;
        new (): HTMLAppLayoutElement;
    };
    interface HTMLAppNavElement extends Components.AppNav, HTMLStencilElement {
    }
    var HTMLAppNavElement: {
        prototype: HTMLAppNavElement;
        new (): HTMLAppNavElement;
    };
    interface HTMLGuideListElement extends Components.GuideList, HTMLStencilElement {
    }
    var HTMLGuideListElement: {
        prototype: HTMLGuideListElement;
        new (): HTMLGuideListElement;
    };
    interface HTMLGuidePageElement extends Components.GuidePage, HTMLStencilElement {
    }
    var HTMLGuidePageElement: {
        prototype: HTMLGuidePageElement;
        new (): HTMLGuidePageElement;
    };
    interface HTMLGuideViewElement extends Components.GuideView, HTMLStencilElement {
    }
    var HTMLGuideViewElement: {
        prototype: HTMLGuideViewElement;
        new (): HTMLGuideViewElement;
    };
    interface HTMLLatestReleaseElement extends Components.LatestRelease, HTMLStencilElement {
    }
    var HTMLLatestReleaseElement: {
        prototype: HTMLLatestReleaseElement;
        new (): HTMLLatestReleaseElement;
    };
    interface HTMLProjectPageElement extends Components.ProjectPage, HTMLStencilElement {
    }
    var HTMLProjectPageElement: {
        prototype: HTMLProjectPageElement;
        new (): HTMLProjectPageElement;
    };
    interface HTMLSkillPointsCardElement extends Components.SkillPointsCard, HTMLStencilElement {
    }
    var HTMLSkillPointsCardElement: {
        prototype: HTMLSkillPointsCardElement;
        new (): HTMLSkillPointsCardElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-layout": HTMLAppLayoutElement;
        "app-nav": HTMLAppNavElement;
        "guide-list": HTMLGuideListElement;
        "guide-page": HTMLGuidePageElement;
        "guide-view": HTMLGuideViewElement;
        "latest-release": HTMLLatestReleaseElement;
        "project-page": HTMLProjectPageElement;
        "skill-points-card": HTMLSkillPointsCardElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    interface AppHome {
    }
    interface AppLayout {
    }
    interface AppNav {
    }
    interface GuideList {
        "guideId": string;
    }
    interface GuidePage {
    }
    interface GuideView {
        "guideId": string;
    }
    interface LatestRelease {
    }
    interface ProjectPage {
        "heroImage"?: string;
        /**
          * @default ''
         */
        "pageTitle"?: string;
        "tagline"?: string;
    }
    interface SkillPointsCard {
        /**
          * @default 'Skill Points'
         */
        "cardTitle"?: string;
        "guideId"?: string;
        /**
          * @default []
         */
        "skills"?: SkillEntry[];
        /**
          * @default []
         */
        "tabs"?: SkillTab[];
    }

    interface GuideListAttributes {
        "guideId": string;
    }
    interface GuideViewAttributes {
        "guideId": string;
    }
    interface ProjectPageAttributes {
        "pageTitle": string;
        "tagline": string;
        "heroImage": string;
    }
    interface SkillPointsCardAttributes {
        "cardTitle": string;
        "guideId": string;
    }

    interface IntrinsicElements {
        "app-home": AppHome;
        "app-layout": AppLayout;
        "app-nav": AppNav;
        "guide-list": Omit<GuideList, keyof GuideListAttributes> & { [K in keyof GuideList & keyof GuideListAttributes]?: GuideList[K] } & { [K in keyof GuideList & keyof GuideListAttributes as `attr:${K}`]?: GuideListAttributes[K] } & { [K in keyof GuideList & keyof GuideListAttributes as `prop:${K}`]?: GuideList[K] } & OneOf<"guideId", GuideList["guideId"], GuideListAttributes["guideId"]>;
        "guide-page": GuidePage;
        "guide-view": Omit<GuideView, keyof GuideViewAttributes> & { [K in keyof GuideView & keyof GuideViewAttributes]?: GuideView[K] } & { [K in keyof GuideView & keyof GuideViewAttributes as `attr:${K}`]?: GuideViewAttributes[K] } & { [K in keyof GuideView & keyof GuideViewAttributes as `prop:${K}`]?: GuideView[K] } & OneOf<"guideId", GuideView["guideId"], GuideViewAttributes["guideId"]>;
        "latest-release": LatestRelease;
        "project-page": Omit<ProjectPage, keyof ProjectPageAttributes> & { [K in keyof ProjectPage & keyof ProjectPageAttributes]?: ProjectPage[K] } & { [K in keyof ProjectPage & keyof ProjectPageAttributes as `attr:${K}`]?: ProjectPageAttributes[K] } & { [K in keyof ProjectPage & keyof ProjectPageAttributes as `prop:${K}`]?: ProjectPage[K] };
        "skill-points-card": Omit<SkillPointsCard, keyof SkillPointsCardAttributes> & { [K in keyof SkillPointsCard & keyof SkillPointsCardAttributes]?: SkillPointsCard[K] } & { [K in keyof SkillPointsCard & keyof SkillPointsCardAttributes as `attr:${K}`]?: SkillPointsCardAttributes[K] } & { [K in keyof SkillPointsCard & keyof SkillPointsCardAttributes as `prop:${K}`]?: SkillPointsCard[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.IntrinsicElements["app-home"] & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-layout": LocalJSX.IntrinsicElements["app-layout"] & JSXBase.HTMLAttributes<HTMLAppLayoutElement>;
            "app-nav": LocalJSX.IntrinsicElements["app-nav"] & JSXBase.HTMLAttributes<HTMLAppNavElement>;
            "guide-list": LocalJSX.IntrinsicElements["guide-list"] & JSXBase.HTMLAttributes<HTMLGuideListElement>;
            "guide-page": LocalJSX.IntrinsicElements["guide-page"] & JSXBase.HTMLAttributes<HTMLGuidePageElement>;
            "guide-view": LocalJSX.IntrinsicElements["guide-view"] & JSXBase.HTMLAttributes<HTMLGuideViewElement>;
            "latest-release": LocalJSX.IntrinsicElements["latest-release"] & JSXBase.HTMLAttributes<HTMLLatestReleaseElement>;
            "project-page": LocalJSX.IntrinsicElements["project-page"] & JSXBase.HTMLAttributes<HTMLProjectPageElement>;
            "skill-points-card": LocalJSX.IntrinsicElements["skill-points-card"] & JSXBase.HTMLAttributes<HTMLSkillPointsCardElement>;
        }
    }
}
