/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppLayout {
    }
    interface AppNav {
    }
    interface ProjectPage {
        "heroImage"?: string;
        /**
          * @default ''
         */
        "pageTitle": string;
        "tagline"?: string;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppLayoutElement extends Components.AppLayout, HTMLStencilElement {
    }
    var HTMLAppLayoutElement: {
        prototype: HTMLAppLayoutElement;
        new (): HTMLAppLayoutElement;
    };
    interface HTMLAppNavElement extends Components.AppNav, HTMLStencilElement {
    }
    var HTMLAppNavElement: {
        prototype: HTMLAppNavElement;
        new (): HTMLAppNavElement;
    };
    interface HTMLProjectPageElement extends Components.ProjectPage, HTMLStencilElement {
    }
    var HTMLProjectPageElement: {
        prototype: HTMLProjectPageElement;
        new (): HTMLProjectPageElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-layout": HTMLAppLayoutElement;
        "app-nav": HTMLAppNavElement;
        "project-page": HTMLProjectPageElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppLayout {
    }
    interface AppNav {
    }
    interface ProjectPage {
        "heroImage"?: string;
        /**
          * @default ''
         */
        "pageTitle"?: string;
        "tagline"?: string;
    }

    interface ProjectPageAttributes {
        "pageTitle": string;
        "tagline": string;
        "heroImage": string;
    }

    interface IntrinsicElements {
        "app-home": AppHome;
        "app-layout": AppLayout;
        "app-nav": AppNav;
        "project-page": Omit<ProjectPage, keyof ProjectPageAttributes> & { [K in keyof ProjectPage & keyof ProjectPageAttributes]?: ProjectPage[K] } & { [K in keyof ProjectPage & keyof ProjectPageAttributes as `attr:${K}`]?: ProjectPageAttributes[K] } & { [K in keyof ProjectPage & keyof ProjectPageAttributes as `prop:${K}`]?: ProjectPage[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.IntrinsicElements["app-home"] & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-layout": LocalJSX.IntrinsicElements["app-layout"] & JSXBase.HTMLAttributes<HTMLAppLayoutElement>;
            "app-nav": LocalJSX.IntrinsicElements["app-nav"] & JSXBase.HTMLAttributes<HTMLAppNavElement>;
            "project-page": LocalJSX.IntrinsicElements["project-page"] & JSXBase.HTMLAttributes<HTMLProjectPageElement>;
        }
    }
}
